apiVersion: apps/v1
kind: Deployment
metadata:
  name: kpc-web
  namespace: kpc-system
  labels:
    app: kpc-web
    component: frontend
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: kpc-web
  template:
    metadata:
      labels:
        app: kpc-web
        component: frontend
    spec:
      containers:
      - name: kpc-web
        image: kpc/web:latest
        ports:
        - containerPort: 3001
          name: http
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: kpc-config
              key: NODE_ENV
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: kpc-config
              key: WEB_PORT
        - name: NEXT_PUBLIC_API_URL
          valueFrom:
            configMapKeyRef:
              name: kpc-config
              key: NEXT_PUBLIC_API_URL
        - name: NEXTAUTH_URL
          value: "http://localhost:3001"
        - name: NEXTAUTH_SECRET
          valueFrom:
            secretKeyRef:
              name: kpc-secrets
              key: NEXTAUTH_SECRET
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3001
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3001
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        volumeMounts:
        - name: tmp
          mountPath: /tmp
      volumes:
      - name: tmp
        emptyDir: {}
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: kpc-web
  namespace: kpc-system
  labels:
    app: kpc-web
    component: frontend
spec:
  type: ClusterIP
  ports:
  - port: 3001
    targetPort: 3001
    protocol: TCP
    name: http
  selector:
    app: kpc-web

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: kpc-web-hpa
  namespace: kpc-system
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: kpc-web
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80